import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import { Header } from '@/app/(core)/components/global/header'
import { Footer } from '@/app/(core)/components/global/footer'

const workSans = localFont({
	src: './fonts/WorkSans_wght.ttf',
	variable: '--font-work-sans',
})

const bebasNeue = localFont({
	src: './fonts/BebasNeue-Regular.ttf',
	variable: '--font-bebas-neue',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${bebasNeue.variable} ${workSans.variable} flex flex-col justify-center items-center `}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
